run:
  go: 1.19

linters:
  disable-all: true
  enable:
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - errcheck # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - unused # Checks Go code for unused constants, variables, functions and types
    - gosimple # Linter for Go source code that specializes in simplifying a code
    - structcheck # Finds unused struct fields
    - varcheck # Finds unused global variables and constants
    - bodyclose # checks whether HTTP response body is closed successfully
    - gosec # Inspects source code for security problems
    - unconvert # Remove unnecessary type conversions
    - goimports # Goimports does everything that gofmt does. Additionally it checks unused imports
    - misspell # Finds commonly misspelled English words in comments
    - gofumpt # Gofumpt checks whether code was gofumpt-ed.
    - stylecheck # Stylecheck is a replacement for golint

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - structcheck
        - varcheck
        - bodyclose
        - gosec
        - unconvert
        - goimports
        - misspell
        - gofumpt
        - stylecheck

linters-settings:
  stylecheck: # https://staticcheck.io/docs/checks
    checks: [
        "all",
        "-ST1000", # Incorrect or missing package comment
        "-ST1003", # Poorly chosen identifier
        "-ST1020", # The documentation of an exported function should start with the function’s name
        "-ST1021", # The documentation of an exported type should start with type’s name
      ]
  staticcheck: # https://staticcheck.io/docs/checks
    checks: [
        "all",
        "-SA1019", # Using a deprecated function, variable, constant or field
      ]
